use crate::constants;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::path::PathBuf;

/// Main struct to hold all types of study materials (pdfs, mds, notes...)
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct StudyMaterial {
    pub id: String,                  // unique ID, uuid generated by the frontend
    pub display_name: String,        // name to be displayed in the UI
    pub original_path: PathBuf,      // original file path
    pub markdown_path: PathBuf,      // markdown location
    pub cover_path: Option<PathBuf>, // cover image path
    pub is_processing: bool,         // whether the material is still being processed
    pub tags: HashSet<String>,       // tags for the material
    pub upload_date: String,         // upload date

    #[serde(skip_serializing)]
    pub extra_instructions: String, // extra instructions for the LLM when processing this material TODO

    pub is_indexed: bool,             // whether chunks are in vector database
    pub chunk_count: Option<u32>,     // number of chunks indexed
    pub last_indexed: Option<String>, // when it was last indexed
    pub url: String,                  // for urls and git repos
}

impl StudyMaterial {
    /// Creates a new StudyMaterial
    pub fn new(
        id: String,
        original: PathBuf,
        markdown: PathBuf,
        cover: PathBuf,
        is_processing: bool,
    ) -> Self {
        let display_name = original
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();

        StudyMaterial {
            id: id,
            display_name: display_name,
            original_path: original,
            markdown_path: markdown,
            cover_path: Some(cover), // Cover might not be accessible yet
            is_processing: is_processing,
            tags: HashSet::new(),
            upload_date: chrono::Utc::now().to_rfc3339(),
            extra_instructions: String::new(),
            is_indexed: false,
            chunk_count: None,
            last_indexed: None,
            url: String::new(),
        }
    }

    // For materials created from URLs
    pub fn new_from_url(
        id: String,
        display_name: String,
        url: String,
        markdown: PathBuf,
        cover: PathBuf,
        is_processing: bool,
    ) -> Self {
        StudyMaterial {
            id: id,
            display_name: display_name,
            original_path: markdown.clone(),
            markdown_path: markdown,
            cover_path: Some(cover), // Cover might not be accessible yet
            is_processing: is_processing,
            tags: HashSet::new(),
            upload_date: chrono::Utc::now().to_rfc3339(),
            extra_instructions: String::new(),
            is_indexed: false,
            chunk_count: None,
            last_indexed: None,
            url: url,
        }
    }
}

pub fn sort_study_materials(
    sort_by: Option<String>,
    mut materials: Vec<StudyMaterial>,
) -> Vec<StudyMaterial> {
    match sort_by.as_deref() {
        Some(constants::NAME_ASC) => {
            materials.sort_by(|a, b| {
                a.display_name
                    .to_lowercase()
                    .cmp(&b.display_name.to_lowercase())
            });
        }
        Some(constants::NAME_DESC) => {
            materials.sort_by(|a, b| {
                b.display_name
                    .to_lowercase()
                    .cmp(&a.display_name.to_lowercase())
            });
        }
        Some(constants::DATE_ASC) => {
            materials.sort_by(|a, b| a.upload_date.cmp(&b.upload_date));
        }
        Some(constants::DATE_DESC) => {
            materials.sort_by(|a, b| b.upload_date.cmp(&a.upload_date));
        }
        _ => {
            // Default sorting: date ascending
            materials.sort_by(|a, b| a.upload_date.cmp(&b.upload_date));
        }
    }

    materials
}
